# Use of basical image jdk
FROM openjdk:17-jdk-slim
# Environment variables
ENV author=LIU
# Root path in the container
WORKDIR /app

# Accept JAR path as a build argument
ARG JAR_PATH

# Copy the jar to container
COPY ${JAR_PATH} app.jar

# Entry point, when container starts, this command will definitively executed to start the java program
ENTRYPOINT ["java","-jar","/app/app.jar"]
